using UnityEngine;
using UnityEngine.Rendering;
using System.Collections;

#pragma warning disable 162

using ImprovedPerlinNoiseProject;

namespace MarchingCubesGPUProject
{
    public class MarchingCubesGPU_4DNoise : MonoBehaviour
    {

        //The size of the voxel array for each dimension
        const int N = 128;

        //The size of the buffer that holds the verts.
        //This is the maximum number of verts that the 
        //marching cube can produce, 5 triangles for each voxel.

        public int seed;

        public float speed = 2.0f;

        public Material drawBuffer;

        public ComputeShader perlinNoise;

        public ComputeShader marchingCubes;

        public ComputeShader normals;

        private ComputeBuffer _meshBuffer, _argsBuffer;

        private RenderTexture _noiseBuffer, _normalsBuffer;

        private GPUPerlinNoise _perlin;

        private int _size;
        private Bounds _bounds;

        void Start()
        {
            //There are 8 threads run per group so N must be divisible by 8.
            if (N % 8 != 0)
                throw new System.ArgumentException("N must be divisible be 8");

            _size = Mathf.RoundToInt(Mathf.Pow(N, 2.7f)) * 3;
            Debug.Log("Init with size " + _size);

            //Holds the voxel values, generated from perlin noise.
            _noiseBuffer = new RenderTexture(N, N, 0, RenderTextureFormat.RHalf, RenderTextureReadWrite.Linear)
                {
                    dimension = TextureDimension.Tex3D,
                    enableRandomWrite = true,
                    useMipMap = false,
                    volumeDepth = N
                };
            _noiseBuffer.Create();
            
            //Holds the normals of the voxels.
            _normalsBuffer = new RenderTexture(N, N, 0, RenderTextureFormat.ARGBHalf, RenderTextureReadWrite.Linear)
                {
                    dimension = TextureDimension.Tex3D,
                    enableRandomWrite = true,
                    useMipMap = false,
                    volumeDepth = N
                };
            _normalsBuffer.Create();

            //Holds the verts generated by the marching cubes.
            _meshBuffer = new ComputeBuffer(_size, sizeof(float) * 8);

            _argsBuffer = new ComputeBuffer(5, sizeof(uint), ComputeBufferType.IndirectArguments);
            _argsBuffer.SetData(new[] {0, 1, 0, 0, 0});
            
            //Make the perlin noise, make sure to load resources to match shader used.
            _perlin = new GPUPerlinNoise(seed);
            _perlin.LoadResourcesFor4DNoise();

            _bounds = new Bounds(Vector3.one * (N * 0.5f), Vector3.one * N);
        }


        void Update()
        {
            //Make the voxels.
            perlinNoise.SetInt("_Width", N);
            perlinNoise.SetInt("_Height", N);
            perlinNoise.SetFloat("_Frequency", 0.02f);
            perlinNoise.SetFloat("_Lacunarity", 2.0f);
            perlinNoise.SetFloat("_Gain", 0.5f);
            perlinNoise.SetFloat("_Time", Time.realtimeSinceStartup * speed);
            perlinNoise.SetTexture(0, "_PermTable1D", _perlin.PermutationTable1D);
            perlinNoise.SetTexture(0, "_PermTable2D", _perlin.PermutationTable2D);
            perlinNoise.SetTexture(0, "_Gradient4D", _perlin.Gradient4D);
            perlinNoise.SetTexture(0, "_Result", _noiseBuffer);

            perlinNoise.Dispatch(0, N / 8, N / 8, N / 8);

            //Make the voxel normals.
            normals.SetInt("_Width", N);
            normals.SetInt("_Height", N);
            normals.SetTexture(0, "_Noise", _noiseBuffer);
            normals.SetTexture(0, "_Result", _normalsBuffer);

            normals.Dispatch(0, N / 8, N / 8, N / 8);

            //Clear the buffer from last frame.
            marchingCubes.SetVector("_Size", new Vector4(N, N, N, 0));
            marchingCubes.SetInt("_BufferSize", _size);
            
            // clear vertex counter
            marchingCubes.SetBuffer(0, "_Counter", _argsBuffer);
            marchingCubes.Dispatch(0, 1, 1, 1);
            
            //Make the mesh verts
            marchingCubes.SetFloat("_Target", 0.0f);
            marchingCubes.SetFloat("_CellSize", 0.2f);
            
            marchingCubes.SetTexture(1, "_Voxels", _noiseBuffer);
            marchingCubes.SetTexture(1, "_Normals", _normalsBuffer);
            marchingCubes.SetBuffer(1, "_Buffer", _meshBuffer);
            marchingCubes.SetBuffer(1, "_Counter", _argsBuffer);

            marchingCubes.Dispatch(1, N / 8, N / 8, N / 8);
            
            drawBuffer.SetBuffer("_Buffer", _meshBuffer);
            drawBuffer.SetPass(0);
            Graphics.DrawProceduralIndirect(drawBuffer, _bounds, MeshTopology.Triangles, _argsBuffer);
        }
        
        void OnDestroy()
        {
            //MUST release buffers.
            _noiseBuffer.Release();
            _meshBuffer.Release();
            _normalsBuffer.Release();
            _argsBuffer.Release();
        }

    }

}





























