
#pragma use_dxc

#include "NBFlipUtils.hlsl"

#pragma target 6.0
#pragma enable_d3d12_debug_symbols

#pragma kernel MakePair
#pragma kernel ClearGrid
#pragma kernel SetRange
#pragma kernel Rearrange

StructuredBuffer<uint> _ParticlesIDR;
RWStructuredBuffer<uint> _ParticlesIDW;

StructuredBuffer<uint> _ParticlesHashR;
RWStructuredBuffer<uint> _ParticlesHashW;

StructuredBuffer<Particle> _ParticlesR;
RWStructuredBuffer<Particle> _ParticlesW;

StructuredBuffer<uint2> _ParticlesRangeR;
RWStructuredBuffer<uint2> _ParticlesRangeW;

RWTexture3D<float> _PressureW;
RWStructuredBuffer<uint2> _CellParticleCountW;

StructuredBuffer<uint> _CounterR;
RWStructuredBuffer<uint> _CounterW;

[numthreads(GROUP_THREADS_X, 1, 1)]
void MakePair (uint3 id : SV_DispatchThreadID)
{
    uint numParticles = _CounterR[0];
    _ParticlesIDW[id.x] = id.x;
    _ParticlesHashW[id.x] = id.x >= numParticles ? 0xFFFFFFFFu : Coord2Idx(PositionCoord(_ParticlesR[id.x].packedPosition));
}

[numthreads(GROUP_THREADS_D3)]
void ClearGrid (uint3 id : SV_DispatchThreadID)
{
    _PressureW[id] = 0.f;
    uint idx = Coord2Idx(id);
    _ParticlesRangeW[idx] = uint2(0, 0);
    _CellParticleCountW[idx] = 0;
}

[numthreads(GROUP_THREADS_X, 1, 1)]
void SetRange(uint3 thread_id : SV_DispatchThreadID)
{
    uint numParticles = _CounterR[0];
    if (thread_id.x >= numParticles) return;
    const uint curr_o_id = thread_id.x;

    uint max_id = numParticles - 1;
    const uint prev_o_id = curr_o_id == 0 ? max_id : curr_o_id - 1;
    const uint next_o_id = curr_o_id == max_id ? 0 : curr_o_id + 1;
    const uint curr_c_id = _ParticlesHashR[curr_o_id];
    const uint prev_c_id = _ParticlesHashR[prev_o_id];
    const uint next_c_id = _ParticlesHashR[next_o_id];

    if (curr_c_id != prev_c_id) _ParticlesRangeW[curr_c_id].x = curr_o_id;
    if (curr_c_id != next_c_id) _ParticlesRangeW[curr_c_id].y = curr_o_id + 1;
}

[numthreads(GROUP_THREADS_X, 1, 1)]
void Rearrange(uint3 id : SV_DispatchThreadID)
{
    uint numParticles = _CounterR[0];
    if (id.x >= numParticles) return;
    int pid = _ParticlesIDR[id.x];
    if (pid >= numParticles) return;
    _ParticlesW[id.x] = _ParticlesR[pid];
}