
#pragma use_dxc
#include "NBFlipUtils.hlsl"

// #pragma target 6.0
#pragma enable_d3d11_debug_symbols

#pragma kernel SetGridType
#pragma kernel SetGridLevel
#pragma kernel ParticlesCounter
#pragma kernel ResampleParticles

StructuredBuffer<int> _ParticlesIDR;
RWStructuredBuffer<int> _ParticlesIDW;

StructuredBuffer<uint> _ParticlesHashR;
RWStructuredBuffer<uint> _ParticlesHashW;

StructuredBuffer<Particle> _ParticlesR;
RWStructuredBuffer<Particle> _ParticlesW;

StructuredBuffer<uint2> _ParticlesRangeR;
RWStructuredBuffer<uint2> _ParticlesRangeW;

RWTexture3D<float> _GridSDFW;
Texture3D<float> _GridSDFR;

Texture3D<uint> _GridTypesR;
RWTexture3D<uint> _GridTypesW;

RWStructuredBuffer<uint> _CounterW;

Texture3D<float4> _VelocityR;

RWTexture3D<float4> _GridCoefficientW;

inline uint GetType(uint3 coord)
{
    if (_GridSDFR[coord] >= Band1) return FLUID;
    int2 range = _ParticlesRangeR[Coord2Idx(coord)];
    return range.y > range.x ? FLUID : AIR;
}

[numthreads(GROUP_THREADS_D3)]
void SetGridType (uint3 id : SV_DispatchThreadID)
{
    uint3 grid_max = _GridSize - 1;

    const uint gridType = GetType(id);
    const uint xp_type = id.x == 0 ? SOLID :            GetType(id + int3(-1, 0, 0));
    const uint xn_type = id.x == grid_max.x ? SOLID :   GetType(id + int3(1, 0, 0));
    const uint yp_type = id.y == 0 ? SOLID :            GetType(id + int3(0, -1, 0));
    const uint yn_type = id.y == grid_max.y ? SOLID :   GetType(id + int3(0, 1, 0));
    const uint zp_type = id.z == 0 ? SOLID :            GetType(id + int3(0, 0, -1));
    const uint zn_type = id.z == grid_max.z ? SOLID :   GetType(id + int3(0, 0, 1));

    float center = 6 - (xp_type >> 1) - (xn_type >> 1) - (yp_type >> 1) - (yn_type >> 1) - (zp_type >> 1) -(zn_type >> 1);
    _GridCoefficientW[id] = gridType == FLUID ? float4(-center, xp_type & 1, yp_type & 1, zp_type & 1) : 0;
    _GridTypesW[id] = PackGridTyped(gridType, xp_type, xn_type, yp_type, yn_type, zp_type, zn_type);
}

[numthreads(GROUP_THREADS_D3)]
void SetGridLevel (uint3 id : SV_DispatchThreadID)
{
    uint gridType = _GridTypesR[id];
    float fill = -1;
    if (IsFluidCell(GetMyType(gridType)))
    {
        uint3 prevTypes = GetPrevTypes(gridType);
        uint3 nextTypes = GetNextTypes(gridType);
        fill = any(prevTypes != FLUID) || any(nextTypes != FLUID) ? 0 : 32;
    }

    _GridSDFW[id] = fill;
}

[numthreads(GROUP_THREADS_D3)]
void ParticlesCounter (uint3 id : SV_DispatchThreadID)
{
    int level = _GridSDFR[id];
    int i = Coord2Idx(id);
    if (level < 0 || level >= Band2)
    {
        _ParticlesRangeW[i] = uint2(0, 0);
        return;
    }
    uint2 range = _ParticlesRangeW[i];
    int count = range.y - range.x;
    int expect = level < 1 ? count : max(8, count);
    int ptr = 0;
    InterlockedAdd(_CounterW[0], expect, ptr);
    for (int j = 0; j < expect; j++)
    {
        _ParticlesIDW[ptr + j] = j < count ? range.x + j : -1; // if need add particle, set -1
    }
    _ParticlesRangeW[i] = uint2(ptr, ptr + expect);
}

[numthreads(GROUP_THREADS_D3)]
void ResampleParticles (uint3 id : SV_DispatchThreadID)
{
    uint2 range = _ParticlesRangeR[Coord2Idx(id)];
    if (range.x >= range.y) return;
    
    int toAdd = 0;
    for (uint i = range.x; i < range.y; i++)
    {
        int pid = _ParticlesIDR[i];
        if (pid == -1)
            toAdd++;
        else
        {
            _ParticlesW[i] = _ParticlesR[pid];
        }
    }
    
    if (toAdd == 0) return;
    
    int existCount = range.y - range.x - toAdd;
    Particle posArr[8];
    for (int i = 0; i < 8; i++)
    {
        if (i < existCount)
        {
            int p = _ParticlesIDR[range.x + i];
            posArr[i] = _ParticlesR[p];
        }
        else
        {
            posArr[i] = (Particle)0;
        }
    }
    
    int3 coord = id;
    float3 origin = ((float3)coord + 0.25f) * _CellSize;
    for (int idx = 0; idx < toAdd; idx++)
    {
        float maxDst = 0;
        float3 selectedPos = origin;
        [unroll]
        for (int i = 0; i < 8; i++)
        { 
            float3 tryPos = origin + float3(i & 1, i >> 1 & 1, i >> 2 & 1) * (_CellSize * 0.5f);
            float minDst = 1000;
            for (int j = 0; j < existCount; j++)
            {
                float3 vec = DecodePosition(posArr[j].packedPosition) - tryPos;
                float len = dot(vec, vec);
                minDst = min(minDst, len);
            }

            if (minDst > maxDst)
            {
                maxDst = minDst;
                selectedPos = tryPos;
            }
        }
        float3 v = SampleGrid(selectedPos, _VelocityR);
        int p = range.x + existCount;
        Particle pa;
        pa.packedPosition = EncodePosition(selectedPos);
        pa.packedVelocity = EncodeVelocity(v);
        _ParticlesW[p] = pa;
        posArr[existCount] = pa;
        existCount++;
    }
}